### ISSUE TITLE
(Android) /storage/emulated/0/Pictures (Permission denied)

### ISSUE THREAD

**Issue by Borisboky** [react-native-community/react-native-camera#762]
I have an issue when I want to take photo. I get big red screen : 

![0-02-04-213d2eb85d3e9adfa830978af11f6f0360e56244ef7ab6577294279063791e2d_full](https://user-images.githubusercontent.com/13819165/27380272-c518b9b4-567e-11e7-82bb-a3e5601787c7.jpg)

`takePicture` function is as follows:

```
takePicture() {
        let target = this.props.toMemory ? {
                target: Camera.constants.CaptureTarget.temp,
                captureQuality: Camera.constants.CaptureQuality["low"],

            } : {
                target: Camera.constants.CaptureTarget.disk,
                captureQuality: Camera.constants.CaptureQuality["low"]
            };

        this.camera.capture(target)
            .then((data) => {
                navigator.geolocation.getCurrentPosition(
                    (position) => {
                        this.props.captured(this.props.request, {path: data.path, data: data.data, longitude: position.coords.longitude, latitude: position.coords.latitude});
                        Actions.pop();
                    },
                    (error) => {
                        this.props.captured(this.props.request, data);
                        Actions.pop();
                    },
                    {enableHighAccuracy: true, timeout: 20000, maximumAge: 1000}
                );
            })
            .catch(err => {
                console.error(err)
            });
    }
```

And `camera component` is as follows :  

```
<Camera
                    style={styles.cameraStyle}
                    ref={cam => this.camera = cam}
                    onZoomChanged={this.onZoomChanged.bind(this)}
                    onFocusChanged={this.onFocusChanged.bind(this)}
                    torchMode={this.state.torch}
                    flashMode={this.state.flash}>
                    {this.imageOverlay()}
                </Camera>
```

I've added permissions in `Android.Manifest`:

```
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.RECORD_VIDEO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Any idea what the problem is?

**Comment by JonnyLinja** [comment]
I'm experiencing the same. What I found is that if you go to Settings -> Application Manager -> Your App -> Permissions -> Enable Storage, it solves the issue.

The next step would be to get the app to request said permissions. I assume https://facebook.github.io/react-native/docs/permissionsandroid.html is how to do it.

**Comment by sibelius** [comment]
permissions on android M is fixed on master 

tks to @ospfranco

**Comment by matias91** [comment]
I also have this problem using the latest version (0.12.0)
I'll try with **_PermissionsAndroid_** 😞

**Comment by sibelius** [comment]
use master

**Comment by owenzip** [comment]
Your device android not allowed your app access storage , Turn on by
Settings > Apps > Choose your app > Permissions > Turn on Storage

**Comment by nicemanis** [comment]
@sibelius I'm using master branch and I still face this issue

**Comment by sibelius** [comment]
try RNCamera

**Comment by nicemanis** [comment]
@sibelius tried to use RNCamera instead, had to change `this.camera.capture` to `this.camera. takePictureAsync`, tried to capture a picture and it returned the data object, but it contains only `base64`, `height` and `width`

**Comment by jgcmarins** [comment]
@nicemanis, we've recently updated master, could you try again, please?

**Comment by nicemanis** [comment]
@jgcmarins now `uri` is available in the response, thanks!

**Comment by jgcmarins** [comment]
Nice one!
Thanks to @jgfidelis \o/

**Comment by nicemanis** [comment]
off-topic: any idea how to optimize camera capture picture performance? Currently it takes around 8-10 seconds on Nexus 5X

**Comment by sibelius** [comment]
on RNCamera?

**Comment by nicemanis** [comment]
yes

**Comment by sibelius** [comment]
could u try with camera module from expo? and see if the problem is the same there?

**Comment by nicemanis** [comment]
also barcode scanning seems to be not working with `RNCamera`, tried with and without barCodeTypes property. Tried to scan with the old `Camera` component, and it was working.

**Comment by sibelius** [comment]
open an issue for qrcode for RNCamera

**Comment by nicemanis** [comment]
`Camera` throws permission error on capture starting from Android SDK 23, regardless if I have asked permissions or not. Tested on `0.12.0` and `master`.

**Comment by AngSin** [comment]
Switching to `temp` from `disk` fixed it for me too
